# Cloudflare Pages Configuration
name = "ibex35dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ibex35-intelligence"
database_id = "d3003b66-214f-44f0-b0de-ef78b7264282"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "ibex35-intelligence"
database_id = "d3003b66-214f-44f0-b0de-ef78b7264282"