# Cloudflare Pages Configuration
name = "ibex35dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ibex35-intelligence"
database_id = "your-database-id"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "ibex35-intelligence"
database_id = "your-production-database-id"

# Scheduled data sync every hour
[triggers]
crons = ["0 * * * *"]