# Cloudflare Pages Configuration
name = "ibex35dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
# Production environment configuration
routes = ["ibex35dashboard.pages.dev/*"]

[env.preview]
# Preview environment configuration
routes = ["*.ibex35dashboard.pages.dev/*"]

# Build configuration
[build]
command = "npm run build"
destination = "dist"

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
from = "/api/*"
to = "https://api.example.com/*"
status = 200

# Functions (if using Cloudflare Workers)
[functions]
directory = "functions"